
// Country list with emoji flags
export const countries = [
  { value: "us", label: "🇺🇸 United States" },
  { value: "ca", label: "🇨🇦 Canada" },
  { value: "gb", label: "🇬🇧 United Kingdom" },
  { value: "au", label: "🇦🇺 Australia" },
  { value: "de", label: "🇩🇪 Germany" },
  { value: "fr", label: "🇫🇷 France" },
  { value: "jp", label: "🇯🇵 Japan" },
  { value: "cn", label: "🇨🇳 China" },
  { value: "in", label: "🇮🇳 India" },
  { value: "br", label: "🇧🇷 Brazil" },
  { value: "mx", label: "🇲🇽 Mexico" },
  { value: "it", label: "🇮🇹 Italy" },
  { value: "es", label: "🇪🇸 Spain" },
  { value: "kr", label: "🇰🇷 South Korea" },
  { value: "ru", label: "🇷🇺 Russia" },
  { value: "za", label: "🇿🇦 South Africa" },
  { value: "ng", label: "🇳🇬 Nigeria" },
  { value: "eg", label: "🇪🇬 Egypt" },
  { value: "sa", label: "🇸🇦 Saudi Arabia" },
  { value: "ae", label: "🇦🇪 United Arab Emirates" },
  { value: "ar", label: "🇦🇷 Argentina" },
  { value: "cl", label: "🇨🇱 Chile" },
  { value: "co", label: "🇨🇴 Colombia" },
  { value: "pe", label: "🇵🇪 Peru" },
  { value: "ve", label: "🇻🇪 Venezuela" },
  { value: "nl", label: "🇳🇱 Netherlands" },
  { value: "be", label: "🇧🇪 Belgium" },
  { value: "se", label: "🇸🇪 Sweden" },
  { value: "no", label: "🇳🇴 Norway" },
  { value: "dk", label: "🇩🇰 Denmark" },
  { value: "fi", label: "🇫🇮 Finland" },
  { value: "pl", label: "🇵🇱 Poland" },
  { value: "at", label: "🇦🇹 Austria" },
  { value: "ch", label: "🇨🇭 Switzerland" },
  { value: "gr", label: "🇬🇷 Greece" },
  { value: "pt", label: "🇵🇹 Portugal" },
  { value: "ie", label: "🇮🇪 Ireland" },
  { value: "nz", label: "🇳🇿 New Zealand" },
  { value: "sg", label: "🇸🇬 Singapore" },
  { value: "my", label: "🇲🇾 Malaysia" },
  { value: "th", label: "🇹🇭 Thailand" },
  { value: "ph", label: "🇵🇭 Philippines" },
  { value: "id", label: "🇮🇩 Indonesia" },
  { value: "vn", label: "🇻🇳 Vietnam" },
  { value: "tr", label: "🇹🇷 Turkey" },
  { value: "il", label: "🇮🇱 Israel" },
  { value: "ua", label: "🇺🇦 Ukraine" },
  { value: "other", label: "🌍 Other Country" }
];

// US States
export const usStates = [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" },
  { value: "DC", label: "District of Columbia" }
];
