
// Country list with emoji flags
export const countries = [
  { value: "United States", label: "🇺🇸 United States" },
  { value: "Canada", label: "🇨🇦 Canada" },
  { value: "United Kingdom", label: "🇬🇧 United Kingdom" },
  { value: "Australia", label: "🇦🇺 Australia" },
  { value: "Germany", label: "🇩🇪 Germany" },
  { value: "France", label: "🇫🇷 France" },
  { value: "Japan", label: "🇯🇵 Japan" },
  { value: "China", label: "🇨🇳 China" },
  { value: "India", label: "🇮🇳 India" },
  { value: "Brazil", label: "🇧🇷 Brazil" },
  { value: "Mexico", label: "🇲🇽 Mexico" },
  { value: "Italy", label: "🇮🇹 Italy" },
  { value: "Spain", label: "🇪🇸 Spain" },
  { value: "South Korea", label: "🇰🇷 South Korea" },
  { value: "Russia", label: "🇷🇺 Russia" },
  { value: "South Africa", label: "🇿🇦 South Africa" },
  { value: "Nigeria", label: "🇳🇬 Nigeria" },
  { value: "Egypt", label: "🇪🇬 Egypt" },
  { value: "Saudi Arabia", label: "🇸🇦 Saudi Arabia" },
  { value: "United Arab Emirates", label: "🇦🇪 United Arab Emirates" },
  { value: "Argentina", label: "🇦🇷 Argentina" },
  { value: "Chile", label: "🇨🇱 Chile" },
  { value: "Colombia", label: "🇨🇴 Colombia" },
  { value: "Peru", label: "🇵🇪 Peru" },
  { value: "Venezuela", label: "🇻🇪 Venezuela" },
  { value: "Netherlands", label: "🇳🇱 Netherlands" },
  { value: "Belgium", label: "🇧🇪 Belgium" },
  { value: "Sweden", label: "🇸🇪 Sweden" },
  { value: "Norway", label: "🇳🇴 Norway" },
  { value: "Denmark", label: "🇩🇰 Denmark" },
  { value: "Finland", label: "🇫🇮 Finland" },
  { value: "Poland", label: "🇵🇱 Poland" },
  { value: "Austria", label: "🇦🇹 Austria" },
  { value: "Switzerland", label: "🇨🇭 Switzerland" },
  { value: "Greece", label: "🇬🇷 Greece" },
  { value: "Portugal", label: "🇵🇹 Portugal" },
  { value: "Ireland", label: "🇮🇪 Ireland" },
  { value: "New Zealand", label: "🇳🇿 New Zealand" },
  { value: "Singapore", label: "🇸🇬 Singapore" },
  { value: "Malaysia", label: "🇲🇾 Malaysia" },
  { value: "Thailand", label: "🇹🇭 Thailand" },
  { value: "Philippines", label: "🇵🇭 Philippines" },
  { value: "Indonesia", label: "🇮🇩 Indonesia" },
  { value: "Vietnam", label: "🇻🇳 Vietnam" },
  { value: "Turkey", label: "🇹🇷 Turkey" },
  { value: "Israel", label: "🇮🇱 Israel" },
  { value: "Ukraine", label: "🇺🇦 Ukraine" },
  { value: "Other", label: "🌍 Other Country" }
];

// US States
export const usStates = [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" },
  { value: "DC", label: "District of Columbia" }
];
